"""Initial migration_2

Revision ID: decdc568548f
Revises: cec0cd13fb3e
Create Date: 2024-10-06 21:47:48.645181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decdc568548f'
down_revision: Union[str, None] = 'cec0cd13fb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['parent_id'], ['id'])
    # ### end Alembic commands ###
